jobs:
  lint:
    runs-on: ubuntu-latest
    environment: release
    name: Test
    steps:
      - name: setup repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "npm"
      - run: npm run lint
    timeout-minutes: 10
  build:
    runs-on: ubuntu-latest
    environment: release
    name: Test
    steps:
      - name: setup repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "npm"
      - run: npm run build
    timeout-minutes: 10
  test:
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    environment: release
    name: Test
    steps:
      - name: setup repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "npm"
      - run: npm run test
    timeout-minutes: 10
name: Test and build
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".editorconfig"
      - ".husky/**"
      - ".lintstagedrc.js"
      - ".mergify.yml"
      - ".nvmrc"
      - "README.md"
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
